// National Cashew Policy 2022–2027 example workspace.
// Data comes from src/data/cashew.json, generated by scripts/build_cashew_data.py
// from the owner's action-level workbook (v5), outcome workbook (v12), Kobo
// XLSForm (v10) and the mid-term review report (final draft).

import raw from "../data/cashew.json" with { type: "json" };
import { formatByUnit } from "./format.ts";
import { koboPercentage, statusWith, type ActionStatus, type Method, type Threshold } from "./rules.ts";

export { koboPercentage };
export type { ActionStatus, Method, Threshold };

export type Cluster = "production" | "processing" | "export";

export interface Ministry {
  code: string;
  short: string;
  name: string;
  nameKm: string;
  y2025: {
    assigned: number | null;
    reported: number | null;
    avgActualPct: number | null;
    avgCappedPct: number | null;
    fully: number;
    largely: number;
    limited: number;
  };
}

export interface ActionIndicator {
  id: string;
  no: number;
  code: string;
  action: number;
  ministry: string;
  label: string;
  labelKm: string;
  targetText: string;
  target: number | null;
  method: Method;
  answerType: string;
  calculation: string;
  question: string;
  questionKm: string;
  constraint: string;
  constraintMsg: string;
  kobo: { group: string; value: string; percentage: string; followup: string; evidence: string; feedback: string };
  y2025: { value: number | string | null; actualPct: number | null; cappedPct: number | null; status: string | null };
}

export interface Action {
  no: number;
  code: string;
  title: string;
  cluster: Cluster;
  workbookPillar: Cluster;
  lead: string;
  ministries: string[];
  responsible: string;
  indicators: string[];
  y2025: { avgActualPct: number | null; avgCappedPct: number | null; fully: number; largely: number; limited: number };
  mtrProgress: string;
  mtrSummary: string;
}

export interface OutcomeIndicator {
  code: string;
  title: string;
  unit: string;
  direction: "increase" | "decrease";
  series: Record<string, number | null>;
  source: string;
  tool: string;
  area: string;
  frequency: string;
  disaggregation: string;
  definition: string;
  note: string;
  testData: boolean;
}

export interface MarketRow {
  destination: string;
  kernel_t: number;
  kernel_usd: number;
  processed_t: number;
  processed_usd: number;
  rcn_t: number;
  rcn_eq_t: number;
}

interface KoboSection {
  name: string;
  ministry: string;
  label: string;
  labelKm: string;
  relevant: string;
  indicators: string[];
}

interface Data {
  mtr: {
    title: string;
    status: string;
    date: string;
    asOf: string;
    goalProgress: string[];
    criteria: Record<string, string>;
    priorities: string[];
    recommendations: Record<string, string[]>;
    nextSteps: string[];
    clusterCounts: Record<string, { actions: number; fully: number; largely: number; limited: number }>;
    method: string;
  };
  koboForm: {
    title: string;
    formId: string;
    version: string;
    defaultLanguage: string;
    rows: number;
    respondentFields: { name: string; type: string; en: string; km: string; hint: string }[];
    perIndicatorFields: { suffix: string; type: string; en: string; km: string; hint: string; required?: boolean }[];
    sections: KoboSection[];
    choices: { list: string; name: string; en: string; km: string }[];
  };
  outcomeIndicators: OutcomeIndicator[];
  topMarkets: Record<string, MarketRow[]>;
  production: { year: number; area_ha: number; production_t: number; source: string }[];
  income: { year: number; price_khr: number; fx: number; income_usd: number }[];
  ministries: Ministry[];
  actions: Action[];
  actionIndicators: ActionIndicator[];
  thresholds: Threshold[];
}

const data = raw as unknown as Data;

export const mtr = data.mtr;
export const koboForm = data.koboForm;
export const ministries = data.ministries;
export const actions = data.actions;
export const actionIndicators = data.actionIndicators;
export const outcomeIndicators = data.outcomeIndicators;
export const topMarkets = data.topMarkets;
export const production = data.production;
export const income = data.income;
export const thresholds = data.thresholds;

export const REPORTING_YEAR = 2025;
export const OUTCOME_YEARS = [2022, 2023, 2024, 2025, 2026, 2027];

export const policy = {
  code: "NCP-2022",
  name: "National Cashew Policy 2022–2027",
  approved: "2023-01-13",
  approvedBy: "Council of Ministers (plenary session)",
  start: "2022-01-01",
  end: "2027-12-31",
  owner: "Ministry of Commerce (MoC)",
  secretariat: "M&E Secretariat, Trade Policy Department, General Department of Trade Promotion, MoC",
  committee: "Inter-Ministerial Committee for Monitoring and Evaluation of the Implementation of the National Cashew Policy 2022–2027 (established mid-2024)",
  partners: "EU-German CAPSAFE and EU-German GATE (technical support)",
  vision:
    "Develop cashew production, processing and markets through inclusive competitiveness to ensure sustainability and economic diversification, making Cambodia a major producer and supplier of cashew products for local, regional and global markets.",
  goals: [
    { code: "G1", cluster: "production" as Cluster, text: "Improve production and product outputs with competitive quality" },
    { code: "G2", cluster: "processing" as Cluster, text: "Promote industrialisation: 25% of the cashew harvest processed domestically by 2027 and at least 50% by 2032" },
    { code: "G3", cluster: "export" as Cluster, text: "Promote exports through market diversification, inter-sectoral export linkages, trade facilitation, lower production costs and market advantage" },
  ],
  alignment: "Pentagonal Strategy – Phase I (2023–2028), pentagon 2: economic diversification and competitiveness",
};

export const clusterLabel: Record<Cluster, string> = {
  production: "Production",
  processing: "Processing",
  export: "Export",
};

export const goalOutcomeCodes: Record<string, string[]> = {
  G1: ["P1", "P2", "P3", "Q1", "Q2"],
  G2: ["PR1", "PR2"],
  G3: ["M1", "M2", "M3"],
  impact: ["S1", "S2", "S3"],
};

export const calendar = [
  { month: "January", activity: "MoC reviews and re-deploys the Kobo form for the new reporting year.", owner: "MoC" },
  { month: "February (week 1)", activity: "MoC sends the kick-off letter, Kobo link and each ministry's indicator extract.", owner: "MoC" },
  { month: "February–March", activity: "Ministries collect figures internally and prepare evidence.", owner: "Ministries" },
  { month: "31 March", activity: "Submission deadline.", owner: "Ministries" },
  { month: "April (week 1)", activity: "Reminders to non-respondents; GDCE data downloaded for the outcome workbook.", owner: "MoC" },
  { month: "April (week 2)", activity: "Export from Kobo, load, run data-quality checks, produce the dashboard.", owner: "MoC" },
  { month: "April (weeks 3–4)", activity: "Verification queries and ministry correction window.", owner: "MoC + ministries" },
  { month: "May (week 1)", activity: "Cashew Committee endorses the consolidated annual report.", owner: "MoC + Committee" },
  { month: "May (week 2)", activity: "Annual report circulated to the Council of Ministers and partners.", owner: "MoC" },
];

// ---- lookups --------------------------------------------------------------

const ministryMap = new Map(ministries.map((m) => [m.code, m]));
const indicatorMap = new Map(actionIndicators.map((i) => [i.id, i]));

export const getMinistry = (code: string) => ministryMap.get(code);
export const ministryShort = (code: string) => ministryMap.get(code)?.short ?? code.toUpperCase();
export const getAction = (code: string) => actions.find((a) => a.code === code);
export const actionByNo = (no: number) => actions.find((a) => a.no === no);
export const getActionIndicator = (codeOrId: string) =>
  indicatorMap.get(codeOrId) ?? actionIndicators.find((i) => i.code === codeOrId);
export const getOutcomeIndicator = (code: string) => outcomeIndicators.find((o) => o.code === code);
export const indicatorsOfAction = (a: Action) => a.indicators.map((id) => indicatorMap.get(id)!).filter(Boolean);
export const indicatorsOfMinistry = (code: string) => actionIndicators.filter((i) => i.ministry === code);
export const actionsLedBy = (code: string) => actions.filter((a) => a.lead === code);
export const actionsJoinedBy = (code: string) => actions.filter((a) => a.lead !== code && a.ministries.includes(code));

// ---- status rules ---------------------------------------------------------

export function thresholdFor(year: number): Threshold {
  return thresholds.find((t) => t.year === year) ?? thresholds[thresholds.length - 1];
}

/**
 * Status from a percentage of the 2027 target, using that year's thresholds
 * (workbook sheet 10_STATUS_THRESHOLDS). Values above 100% count as 100% for
 * status only; the actual percentage stays visible elsewhere.
 */
export function statusFor(pct: number | null | undefined, year: number): ActionStatus | null {
  return statusWith(pct, thresholdFor(year));
}

export function actionStatus(a: Action, year = REPORTING_YEAR): ActionStatus | null {
  return statusFor(a.y2025.avgCappedPct, year);
}

export interface StatusCounts {
  fully: number;
  largely: number;
  limited: number;
  noData: number;
  total: number;
  completion: number | null; // average capped %, 0–100
}

export function countStatuses(pcts: (number | null)[], year = REPORTING_YEAR): StatusCounts {
  const c: StatusCounts = { fully: 0, largely: 0, limited: 0, noData: 0, total: pcts.length, completion: null };
  const valid: number[] = [];
  for (const p of pcts) {
    const s = statusFor(p, year);
    if (s === "Fully Achieved") c.fully++;
    else if (s === "Largely Achieved") c.largely++;
    else if (s === "Limited Progress") c.limited++;
    else c.noData++;
    if (p !== null && Number.isFinite(p)) valid.push(Math.min(p, 100));
  }
  c.completion = valid.length ? valid.reduce((s, v) => s + v, 0) / valid.length : null;
  return c;
}

export const actionCounts = (list: Action[], year = REPORTING_YEAR) =>
  countStatuses(list.map((a) => a.y2025.avgCappedPct), year);

export const indicatorCounts = (list: ActionIndicator[], year = REPORTING_YEAR) =>
  countStatuses(list.map((i) => i.y2025.cappedPct), year);

export function ministryCompletion(code: string) {
  return indicatorCounts(indicatorsOfMinistry(code));
}

// ---- outcome trend ----------------------------------------------------------

export type Trend = "Improving" | "Declining" | "No change" | "No data";

/** Direction-aware change against the 2022 baseline (outcome workbook trend logic). */
export function outcomeTrend(o: OutcomeIndicator, year: number): { trend: Trend; change: number | null; pctChange: number | null } {
  const base = o.series["2022"];
  const cur = o.series[String(year)];
  if (base === null || base === undefined || cur === null || cur === undefined) return { trend: "No data", change: null, pctChange: null };
  const change = cur - base;
  const pctChange = base !== 0 ? (change / base) * 100 : null;
  if (Math.abs(change) < 1e-9) return { trend: "No change", change, pctChange };
  const better = o.direction === "increase" ? change > 0 : change < 0;
  return { trend: better ? "Improving" : "Declining", change, pctChange };
}

/** First year with a value, used when a series has no 2022 baseline. */
export function firstValueYear(o: OutcomeIndicator): number | null {
  for (const y of OUTCOME_YEARS) if (o.series[String(y)] !== null && o.series[String(y)] !== undefined) return y;
  return null;
}

export function formatOutcome(o: OutcomeIndicator, v: number | null | undefined): string {
  return formatByUnit(o.unit, v);
}

export function formatValue(i: ActionIndicator, v = i.y2025.value): string {
  if (v === null || v === undefined || v === "") return "Not reported";
  if (typeof v === "string") return ({ completed: "Completed", in_progress: "In progress", not_started: "Not yet started" } as Record<string, string>)[v] ?? v;
  const unit = i.method === "percent_complete" ? "%" : "";
  return `${v.toLocaleString("en-GB", { maximumFractionDigits: 2 })}${unit}`;
}

export function pct(v: number | null | undefined, digits = 0) {
  if (v === null || v === undefined || !Number.isFinite(v)) return "—";
  return `${v.toLocaleString("en-GB", { maximumFractionDigits: digits })}%`;
}

export const dataNotes = [
  "Action values, percentages and statuses: 2025 reporting year from the Action-Level workbook v5 (15 May 2026), sheet 05_LATEST_VALID_DATA.",
  "Action titles, responsible institutions and progress summaries: MTR report final draft (25 May 2026), tables 4–6, situation as of mid-2025.",
  "Clusters follow the MTR (actions 1–17 production, 18–28 processing, 29–44 export). Workbook v5 groups 1–16 / 17–32 / 33–44, so its pillar charts differ.",
  "The MTR counts 15 fully / 23 largely / 6 limited using a 50% cut-off; the workbook's 2025 threshold is 40%, giving 11 / 27 / 6.",
  "Outcome indicators Q1, Q2, PR1, PR2, S2 and S3 come from Kobo processor-survey rows that the outcome workbook marks as testing/demo data.",
  "Evidence: the 2025 workbook records no evidence files (Evidence_Count 0) and narratives as N/A for all 108 indicators.",
];
