"""Generate supabase/seed/*.sql (the Cashew example workspace, in five parts) from src/data/cashew.json.

Loads structure, indicators, targets, the approved reporting-year 2025 ministry
submissions (values from the Kobo export, endorsed May 2026) and the outcome
series 2022-2025. The illustrative 2026 records shown on the website are NOT
loaded. No personal data: respondent names and phone numbers are left empty
and no user accounts are created.

IDs are deterministic (uuid5), so the seed can be regenerated without changing
keys. Run:  python3 scripts/build_supabase_seed.py
"""

import hashlib
import json
import os
import uuid

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
DATA = json.load(open(os.path.join(ROOT, "src", "data", "cashew.json"), encoding="utf-8"))
NS = uuid.UUID("6f1c0a52-4d1e-4c8e-9a51-2b7d3c0e9f10")

POLICY = {
    "code": "NCP-2022",
    "name": "National Cashew Policy 2022–2027",
    "vision": "Develop cashew production, processing and markets through inclusive competitiveness to ensure sustainability "
              "and economic diversification, making Cambodia a major producer and supplier of cashew products for local, "
              "regional and global markets.",
    "start": "2022-01-01", "end": "2027-12-31", "approved_on": "2023-01-13",
    "approved_by": "Council of Ministers (plenary session)",
}
GOALS = [
    ("G1", "production", "Improve production and product outputs with competitive quality"),
    ("G2", "processing", "Promote industrialisation: 25% of the cashew harvest processed domestically by 2027 and at least 50% by 2032"),
    ("G3", "export", "Promote exports through market diversification, inter-sectoral export linkages, trade facilitation, lower production costs and market advantage"),
]
GOAL_OUTCOMES = {"G1": ["P1", "P2", "P3", "Q1", "Q2"], "G2": ["PR1", "PR2"], "G3": ["M1", "M2", "M3"]}
AREA = {"Production": "production", "Quality": "quality", "Processing": "processing", "Market": "market", "Socio-economic": "socio-economic"}
# Reporting years. 2023-2024 exist only to hold the outcome series; no action
# reporting happened then, so their thresholds (copied from 2025) are never used.
YEARS = [
    (2023, 40, "2024-03-31", "closed"),
    (2024, 40, "2025-03-31", "closed"),
]
YEARS += [(t["year"], t["largely"], f"{t['year'] + 1}-03-31", "closed" if t["year"] == 2025 else "upcoming") for t in DATA["thresholds"]]
KOBO_PUBLISHED = "2026-05-12"  # from the version label 2026051204


PART = "@@part:"
HEADER = """-- Cashew example workspace, part {name}. GENERATED by scripts/build_supabase_seed.py
-- from src/data/cashew.json; do not edit by hand. Run the parts in order.
-- Contains no personal data and no user accounts. Illustrative 2026 records are not loaded.
begin;
set constraints all deferred;

"""


def uid(*parts):
    return str(uuid.uuid5(NS, "/".join(str(p) for p in parts)))


def q(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def insert(table, rows):
    if not rows:
        return ""
    cols = list(rows[0].keys())
    body = ",\n".join("  (" + ", ".join(q(r[c]) for c in cols) + ")" for r in rows)
    return f"insert into {table} ({', '.join(cols)}) values\n{body};\n\n"


def main():
    ws = uid("workspace")
    out = [PART + "01_structure"]
    out.append(insert("workspaces", [{"id": ws, "code": "cashew-moc", "name": "Cashew Policy M&E (MoC)", "timezone": "Asia/Phnom_Penh",
                                      "default_language": "km", "status": "active"}]))

    ministries = [{"id": uid("ministry", m["code"]), "workspace_id": ws, "code": m["code"], "short_name": m["short"],
                   "name_en": m["name"], "name_km": m.get("nameKm"),
                   "type": "ministry" if m["code"] in ("maff", "moe", "moc", "moi", "mef", "mowram", "mrd", "misti", "mot", "mome", "mptc", "mpwt") else "institution",
                   "status": "active"} for m in DATA["ministries"]]
    out.append(insert("ministries", ministries))

    pol = uid("policy", POLICY["code"])
    out.append(insert("policies", [{"id": pol, "workspace_id": ws, "code": POLICY["code"], "name_en": POLICY["name"], "vision": POLICY["vision"],
                                    "start_date": POLICY["start"], "end_date": POLICY["end"], "approved_on": POLICY["approved_on"],
                                    "approved_by": POLICY["approved_by"], "owner_ministry_id": uid("ministry", "moc"), "status": "active"}]))
    out.append(insert("goals", [{"id": uid("goal", g), "workspace_id": ws, "policy_id": pol, "code": g, "text_en": t, "sort_order": i + 1}
                                for i, (g, _, t) in enumerate(GOALS)]))
    out.append(insert("clusters", [{"id": uid("cluster", c), "workspace_id": ws, "policy_id": pol, "goal_id": uid("goal", g), "code": c,
                                    "name_en": c.capitalize(), "sort_order": i + 1} for i, (g, c, _) in enumerate(GOALS)]))
    out.append(insert("programmes", [{"id": uid("programme", m["code"]), "workspace_id": ws, "policy_id": pol, "ministry_id": uid("ministry", m["code"]),
                                      "code": f"PRG-{m['short'].upper()}", "name_en": f"{m['short']} programme under the National Cashew Policy",
                                      "start_date": POLICY["start"], "end_date": POLICY["end"], "status": "active"} for m in DATA["ministries"]]))

    actions, links = [], []
    for a in DATA["actions"]:
        actions.append({"id": uid("action", a["no"]), "workspace_id": ws, "policy_id": pol, "programme_id": uid("programme", a["lead"]),
                        "cluster_id": uid("cluster", a["cluster"]), "number": a["no"], "code": a["code"], "title_en": a["title"],
                        "responsible_text": a.get("responsible"), "status": "active"})
        for m in dict.fromkeys([a["lead"]] + a["ministries"]):
            links.append({"id": uid("action_ministry", a["no"], m), "workspace_id": ws, "action_id": uid("action", a["no"]),
                          "ministry_id": uid("ministry", m), "role": "lead" if m == a["lead"] else "contributing"})
    out.append(insert("actions", actions))
    out.append(insert("action_ministries", links))

    out.append(insert("reporting_years", [{"id": uid("year", y), "workspace_id": ws, "year": y, "starts_on": f"{y}-01-01", "ends_on": f"{y}-12-31",
                                           "deadline": d, "largely_threshold_pct": t, "fully_threshold_pct": 100, "status": s}
                                          for y, t, d, s in YEARS]))

    # ---- indicators, versions, targets -------------------------------------
    inds, vers, tgts, bases = [], [], [], []
    for i in DATA["actionIndicators"]:
        iid = uid("indicator", i["code"])
        inds.append({"id": iid, "workspace_id": ws, "code": i["code"], "external_id": i["id"], "level": "action",
                     "action_id": uid("action", i["action"]), "goal_id": None, "reporting_ministry_id": uid("ministry", i["ministry"]),
                     "area": None, "active_version_id": uid("indicator_version", i["code"], 1), "status": "active"})
        unit = "status" if i["method"] == "milestone" else ("%" if i["method"] == "percent_complete" else ("days" if i["method"] == "inverse_time" else "count"))
        vers.append({"id": uid("indicator_version", i["code"], 1), "workspace_id": ws, "indicator_id": iid, "version_no": 1,
                     "label_en": i["label"].strip(), "label_km": i.get("labelKm"), "unit": unit, "method": i["method"],
                     "direction": "decrease" if i["method"] == "inverse_time" else "increase", "formula_text": i.get("calculation"),
                     "frequency": "annual", "data_source": "Ministry annual report (Kobo)", "effective_from": "2025-01-01", "locked": False})
        tgts.append({"id": uid("target", i["code"], 2027), "workspace_id": ws, "indicator_id": iid, "year": 2027, "revision_no": 1,
                     "value": i["target"], "target_text": i["targetText"], "is_current": True})
    for o in DATA["outcomeIndicators"]:
        iid = uid("indicator", o["code"])
        goal = next((g for g, codes in GOAL_OUTCOMES.items() if o["code"] in codes), None)
        inds.append({"id": iid, "workspace_id": ws, "code": o["code"], "external_id": None, "level": "outcome", "action_id": None,
                     "goal_id": uid("goal", goal) if goal else None, "reporting_ministry_id": None, "area": AREA[o["area"]],
                     "active_version_id": uid("indicator_version", o["code"], 1), "status": "active"})
        vers.append({"id": uid("indicator_version", o["code"], 1), "workspace_id": ws, "indicator_id": iid, "version_no": 1,
                     "label_en": o["title"], "label_km": None, "unit": o["unit"], "method": "baseline_trend", "direction": o["direction"],
                     "formula_text": o.get("definition"), "frequency": o["frequency"].lower(), "data_source": o["source"],
                     "effective_from": "2022-01-01", "locked": True})
        v2022 = o["series"].get("2022")
        bases.append({"id": uid("baseline", o["code"]), "workspace_id": ws, "indicator_id": iid, "year": 2022, "value": v2022,
                      "missing_reason": None if v2022 is not None else "No data collected before 2025", "source": o["source"]})
    out.append(PART + "02_indicators")
    out.append(insert("indicators", inds))
    out.append(insert("indicator_versions", vers))
    out.append(PART + "03_targets_forms")
    out.append(insert("targets", tgts))
    out.append(insert("baselines", bases))

    # ---- form ----------------------------------------------------------------
    k = DATA["koboForm"]
    form, fv = uid("form", "cashew-indicator-report"), uid("form_version", k["version"])
    schema = json.dumps(k, ensure_ascii=False, sort_keys=True)
    out.append(insert("forms", [{"id": form, "workspace_id": ws, "code": "cashew-indicator-report", "title_en": k["title"], "level": "action",
                                 "channel": "kobo", "kobo_asset_id": None, "active_version_id": fv, "status": "published"}]))
    out.append(insert("form_versions", [{"id": fv, "workspace_id": ws, "form_id": form, "version_label": k["version"], "schema_json": schema,
                                         "schema_hash": hashlib.sha256(schema.encode()).hexdigest(), "published_at": KOBO_PUBLISHED,
                                         "change_note": "Imported from the Kobo XLSForm"}]))
    qs, n = [], 0
    for f in k["respondentFields"]:
        n += 1
        qs.append({"id": uid("question", fv, f["name"]), "workspace_id": ws, "form_version_id": fv, "field_name": f["name"], "indicator_id": None,
                   "purpose": "respondent", "type": "select_one" if f["type"].startswith("select_one") else ("date" if f["type"] == "date" else "text"),
                   "label_en": f["en"], "label_km": f.get("km") or None, "hint_en": f.get("hint") or None, "required": True,
                   "constraint_rule": None, "sort_order": n})
    per = {f["suffix"]: f for f in k["perIndicatorFields"]}
    for i in DATA["actionIndicators"]:
        iid = uid("indicator", i["code"])
        vtype = "select_one" if i["answerType"].startswith("select_one") else i["answerType"]
        n += 5  # value question plus the four repeated ones generated below
        qs.append({"id": uid("question", fv, i["kobo"]["value"]), "workspace_id": ws, "form_version_id": fv, "field_name": i["kobo"]["value"],
                   "indicator_id": iid, "purpose": "value", "type": vtype, "label_en": i["question"], "label_km": i.get("questionKm"),
                   "hint_en": f"2025 reported progress: {i['y2025']['value']}.", "required": True,
                   "constraint_rule": i.get("constraint"), "sort_order": n - 4})
    out.append(PART + "04_questions")
    out.append(insert("questions", qs))
    # The four questions repeated for every indicator (same wording each time):
    # ind_xxx_percentage, _followup, _evidence, _feedback, placed after ind_xxx_value.
    repeated = [("percentage", "_percentage", "calculate", False), ("narrative", "_followup", "text", True),
                ("evidence", "_evidence", "file", False), ("challenge", "_feedback", "text", False)]
    values = ",\n".join(f"    ({q(pu)}, {q(sf)}, {q(ty)}, {q(per[sf]['en'])}, {q(per[sf]['km'] or None)}, {q(per[sf]['hint'] or None)}, {q(rq)}, {k + 1})"
                        for k, (pu, sf, ty, rq) in enumerate(repeated))
    out.append(f"""insert into questions (id, workspace_id, form_version_id, field_name, indicator_id, purpose, type, label_en, label_km,
                       hint_en, required, sort_order)
select md5('question/' || v.form_version_id || '/' || f.name)::uuid, v.workspace_id, v.form_version_id, f.name,
       v.indicator_id, r.purpose, r.type, r.label_en, r.label_km, r.hint_en, r.required, v.sort_order + r.pos
from questions v
cross join (values
{values}
) as r(purpose, suffix, type, label_en, label_km, hint_en, required, pos)
cross join lateral (select replace(v.field_name, '_value', r.suffix) as name) f
where v.form_version_id = {q(fv)} and v.purpose = 'value';

""")
    n_questions = len(qs) + 4 * len(DATA["actionIndicators"])

    # ---- reporting year 2025: approved submissions ---------------------------
    y25 = uid("year", 2025)
    subs, revs, answers = [], [], []
    for m in DATA["ministries"]:
        sid, rid = uid("submission", 2025, m["code"]), uid("revision", 2025, m["code"], 1)
        subs.append({"id": sid, "workspace_id": ws, "code": f"RY2025-{m['short'].upper()}", "ministry_id": uid("ministry", m["code"]),
                     "reporting_year_id": y25, "form_id": form, "state": "draft", "current_revision_id": rid, "approved_revision_id": None,
                     "source": "kobo_import", "is_illustrative": False})
        revs.append({"id": rid, "workspace_id": ws, "submission_id": sid, "revision_no": 1, "form_version_id": fv, "state": "draft"})
        for i in (x for x in DATA["actionIndicators"] if x["ministry"] == m["code"]):
            v = i["y2025"]["value"]
            answers.append({"id": uid("answer", 2025, i["code"]), "workspace_id": ws, "revision_id": rid, "indicator_id": uid("indicator", i["code"]),
                            "indicator_version_id": uid("indicator_version", i["code"], 1),
                            "value_number": None if i["method"] == "milestone" else v,
                            "value_choice": v if i["method"] == "milestone" else None,
                            "narrative": None})
    out.append(PART + "05_submissions_results")
    out.append(insert("submissions", subs))
    out.append(insert("submission_revisions", revs))
    out.append("-- pct_of_target is calculated by the answers_guard trigger\n")
    out.append(insert("answers", answers))
    out.append("""-- Approve (the 2025 cycle was verified and endorsed outside the platform, May 2026)
update submission_revisions set state = 'submitted', submitted_at = '2026-05-11' where workspace_id = '%(ws)s';
update submission_revisions set state = 'approved' where workspace_id = '%(ws)s';
update submissions set state = 'approved', approved_revision_id = current_revision_id where workspace_id = '%(ws)s';

insert into results (id, workspace_id, indicator_id, reporting_year_id, revision_no, indicator_version_id, target_id,
                     value, value_choice, pct_of_target, status, source_type, source_answer_id, state, approved_at)
select a.id, a.workspace_id, a.indicator_id, y.id, 1, a.indicator_version_id, (current_target(a.indicator_id)).id,
       a.value_number, a.value_choice, a.pct_of_target,
       status_for(a.pct_of_target, y.largely_threshold_pct, y.fully_threshold_pct),
       'answer', a.id, 'approved', '2026-05-11'
from answers a
join submission_revisions r on r.id = a.revision_id
join submissions s on s.id = r.submission_id
join reporting_years y on y.id = s.reporting_year_id
where a.workspace_id = '%(ws)s';

update indicator_versions set locked = true where workspace_id = '%(ws)s' and not locked;

""" % {"ws": ws})

    # ---- outcome results 2023-2025 (2022 is the baseline) --------------------
    res = []
    for o in DATA["outcomeIndicators"]:
        for y in ("2023", "2024", "2025"):
            v = o["series"].get(y)
            if v is None:
                continue
            res.append({"id": uid("result", o["code"], y), "workspace_id": ws, "indicator_id": uid("indicator", o["code"]),
                        "reporting_year_id": uid("year", int(y)), "revision_no": 1, "indicator_version_id": uid("indicator_version", o["code"], 1),
                        "value": v, "source_type": "survey" if o["tool"] == "Kobo" else "administrative",
                        "source_note": f"{o['source']}: {o['note']}", "state": "approved", "is_test_data": o["testData"]})
    out.append(insert("results", res))

    out.append(insert("reports", [
        {"id": uid("report", "AR-2025"), "workspace_id": ws, "code": "AR-2025", "title_en": "Annual report, reporting year 2025", "type": "annual",
         "reporting_year_id": y25, "scope": "policy"},
        {"id": uid("report", "MTR"), "workspace_id": ws, "code": "MTR-2025", "title_en": "Mid-term review of the National Cashew Policy", "type": "mtr",
         "reporting_year_id": y25, "scope": "policy"},
    ]))

    folder = os.path.join(ROOT, "supabase", "seed")
    os.makedirs(folder, exist_ok=True)
    for f in os.listdir(folder):
        if f.endswith(".sql"):
            os.remove(os.path.join(folder, f))
    parts, name = {}, None
    for chunk in out:
        if chunk.startswith(PART):
            name = chunk[len(PART):]
            parts[name] = []
        else:
            parts[name].append(chunk)
    for name, chunks in parts.items():
        with open(os.path.join(folder, name + ".sql"), "w", encoding="utf-8") as fh:
            fh.write(HEADER.format(name=name) + "".join(chunks).rstrip() + "\n\ncommit;\n")
    path = folder
    print(f"wrote {path}: {len(ministries)} ministries, {len(actions)} actions, {len(inds)} indicators, {n_questions} questions, "
          f"{len(subs)} submissions, {len(answers)} answers, {len(res)} outcome results")


if __name__ == "__main__":
    main()
